name: social-rotation-backend
services:
- name: api
  source_dir: /
  github:
    repo: BOSS_GITHUB_USERNAME/Rebrand-Social-rotation
    branch: main
  build_command: bundle install
  run_command: bin/start.sh
  environment_slug: ruby
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /up
  routes:
  - path: /
  envs:
  - key: RAILS_ENV
    value: production
  - key: RAILS_MASTER_KEY
    value: YOUR_MASTER_KEY_HERE
  - key: DATABASE_URL
    value: ${dev-db-045706.DATABASE_URL}
  - key: JWT_SECRET_KEY
    value: YOUR_JWT_SECRET_HERE
  - key: FRONTEND_URL
    value: https://social-rotation-frontend.ondigitalocean.app
  - key: DO_SPACES_KEY
    value: YOUR_DO_SPACES_KEY
  - key: DO_SPACES_SECRET
    value: YOUR_DO_SPACES_SECRET
  - key: DO_SPACES_REGION
    value: sfo2
  - key: DO_SPACES_BUCKET
    value: YOUR_SPACE_NAME
  - key: DO_SPACES_ENDPOINT
    value: https://sfo2.digitaloceanspaces.com
